version: "3.8"
networks:
  mealpedant-net:
    name: mealpedant-net
services:
  mealpedant_postgres:
    image: mealpedant_postgres:0.0.1
    container_name: mealpedant_postgres
    hostname: mealpedant_postgres
    build:
      context: /workspaces/mealpedant
      dockerfile: ./docker/dockerfile/postgres.dev.Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    env_file: ./env/.postgres.env
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    shm_size: 256MB
    volumes:
      - /workspaces/mealpedant/db_data/pg_data:/pg_data
    ports:
      - 127.0.0.1:5434:5434
    command: -p 5434
    networks:
      - mealpedant-net
    logging:
      options:
        max-size: 10m
    healthcheck:
      test: ["CMD", "/healthcheck/health_postgres.sh"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256m
  mealpedant_redis:
    image: mealpedant_redis:0.0.1
    container_name: mealpedant_redis
    hostname: mealpedant_redis
    build:
      context: /workspaces/mealpedant
      dockerfile: ./docker/dockerfile/redis.Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    env_file: ./env/.redis.env
    volumes:
      - /workspaces/mealpedant/db_data/redis_data:/redis_data
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    ports:
      - 127.0.0.1:6381:6381
    networks:
      - mealpedant-net
    logging:
      options:
        max-size: 10m
    healthcheck:
      test: ["CMD", "/healthcheck/health_redis.sh"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 32M
  mealpedant_api:
    image: mealpedant_api:0.0.1
    container_name: mealpedant_api
    hostname: mealpedant_api
    build:
      context: /workspaces/mealpedant
      dockerfile: docker/dockerfile/api.Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    volumes:
      - /workspaces/mealpedant/location_local/backups:/backups
      - /workspaces/mealpedant/location_local/static/converted:/photo_converted
      - /workspaces/mealpedant/location_local/static/original:/photo_original
      - /dev/shm:/logs
      - /workspaces/mealpedant/location_local:/static:ro
      - /workspaces/mealpedant/docker/env:/app_env:ro
      - /workspaces/mealpedant/db_data/redis_data:/redis_data:ro
    ports:
      - "127.0.0.1:8899:8899"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant-net
    logging:
      options:
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 128m
    healthcheck:
      test: ["CMD", "/healthcheck/health_api.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mealpedant_postgres:
        condition: service_healthy
      mealpedant_redis:
        condition: service_healthy