
networks:
  mealpedant-net:
    name: mealpedant-net
services:
  mealpedant_postgres:
    hostname: mealpedant_postgres
    image: mealpedant_postgres:1.5.11
    container_name: mealpedant_postgres
    build:
      context:  $HOME/mealpedant_api.d/
      dockerfile: $HOME/mealpedant_api.d/docker/dockerfile/postgres.Dockerfile
    env_file: $HOME/mealpedant_api.d/docker/env/.postgres.env
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    shm_size: 256MB
    volumes:
      - $HOME/databases.d/mealpedant/pg_data:/pg_data
    networks:
      - mealpedant-net
    command: -p 5434
    healthcheck:
      test: ["CMD", "/healthcheck/health_postgres.sh"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
  mealpedant_redis:
    image: mealpedant_redis:1.5.11
    container_name: mealpedant_redis
    hostname: mealpedant_redis
    build:
      context:  $HOME/mealpedant_api.d/
      dockerfile: $HOME/mealpedant_api.d/docker/dockerfile/redis.Dockerfile
    env_file: $HOME/mealpedant_api.d/docker/env/.redis.env
    volumes:
      - $HOME/databases.d/mealpedant/redis_data:/redis_data
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant-net
    healthcheck:
      test: ["CMD", "/healthcheck/health_redis.sh"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 32M
  mealpedant_api:
    image: mealpedant_api:1.5.11
    container_name: mealpedant_api
    hostname: mealpedant_api
    build:
      context: $HOME/mealpedant_api.d/
      dockerfile: $HOME/mealpedant_api.d/docker/dockerfile/api.Dockerfile
    volumes:
      - /srv/backup/mealpedant:/backups
      - /srv/www/static_mealpedant:/static:ro
      - /srv/www/static_mealpedant/converted:/photo_converted
      - /srv/www/static_mealpedant/original:/photo_original
      - $HOME/databases.d/mealpedant/redis_data:/redis_data:ro
      - $HOME/logs.d/mealpedant:/logs
      - $HOME/mealpedant_api.d/docker/env/.api.env:/app_env/.api.env:ro
    ports:
      - "127.0.0.1:8899:8899"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant-net
    logging:
      options:
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD", "/healthcheck/health_api.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mealpedant_postgres:
        condition: service_healthy
      mealpedant_redis:
        condition: service_healthy