version: "3.8"
networks:
  mealpedant-net:
    name: mealpedant-net
services:
  mealpedant_postgres:
    hostname: mealpedant_postgres
    image: mealpedant_postgres:1.0.3
    container_name: mealpedant_postgres
    build:
      context:  $HOME/mealpedant_api/
      dockerfile: $HOME/mealpedant_api/docker/dockerfile/postgres.Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    env_file: $HOME/mealpedant_api/docker/env/.postgres.env
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    shm_size: 256MB
    volumes:
      - $HOME/databases/mealpedant/pg_data:/pg_data
    networks:
      - mealpedant-net
    command: -p 5434
    healthcheck:
      test: ["CMD", "/healthcheck/health_postgres.sh"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
  mealpedant_redis:
    image: mealpedant_redis:1.0.3
    container_name: mealpedant_redis
    hostname: mealpedant_redis
    build:
      context:  $HOME/mealpedant_api/
      dockerfile: $HOME/mealpedant_api/docker/dockerfile/redis.Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    env_file: $HOME/mealpedant_api/docker/env/.redis.env
    volumes:
      - $HOME/databases/mealpedant/redis_data:/redis_data
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant-net
    healthcheck:
      test: ["CMD", "/healthcheck/health_redis.sh"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 32M
  mealpedant_api:
    image: mealpedant_api:1.0.3
    container_name: mealpedant_api
    hostname: mealpedant_api
    build:
      context: $HOME/mealpedant_api/
      dockerfile: docker/dockerfile/api.Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    volumes:
      - /srv/backup/mealpedant:/backups
      - /srv/www/static_mealpedant/converted:/photo_converted
      - /srv/www/static_mealpedant/original:/photo_original
      - $HOME/logs/mealpedant:/logs
      - /srv/www/static_mealpedant:/static:ro
      - $HOME/mealpedant_api/docker/env/.api.env:/app_env/.api.env:ro
      - $HOME/databases/mealpedant/redis_data:/redis_data:ro
    ports:
      - "127.0.0.1:8899:8899"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant-net
    logging:
      options:
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD", "/healthcheck/health_api.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mealpedant_postgres:
        condition: service_healthy
      mealpedant_redis:
        condition: service_healthy