name: Release CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      ####################################
      ## Build binaries for release page #
      ####################################

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: build x86_64
        run: cargo build --release

      - name: compress mealpedant_linux_x86_64 binary
        run: tar -C target/release -czf ./mealpedant_linux_x86_64.tar.gz mealpedant

      ###################
      ## Create release #
      ###################

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: ".github/release-body.md"
          draft: false
          files: |
             mealpedant_linux_x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}