name: Release CI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
       # Build for linux x86_64
      - name: build release linux_x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: compress mealpedant_linux_x86_64 binary
        run: tar -C target/release -czf ./mealpedant_linux_x86_64.tar.gz mealpedant

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: ".github/release-body.md"
          draft: false
          files: |
             mealpedant_linux_x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}